//go:build ignore

// gen_forest.go generates languages_forest.go from go-sitter-forest sub-packages.
//
// Usage:
//
//	go run gen_forest.go [-forest-dir ../../_tmp_sitter_forest/go-sitter-forest-main]
//
// This scans the forest directory for binding.go files, extracts package names,
// and generates a Go source file that imports all ~505 grammars and registers
// them via registerBuiltinLanguages().
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"time"
)

// skipDirs lists directories to exclude from generation.
// These are known broken parsers per PARSERS.md or cause build issues.
var skipDirs = map[string]bool{
	"fastbuild": true, // generate never completes (15min)
}

type langEntry struct {
	Dir       string // directory name, e.g. "python"
	Alias     string // import alias, e.g. "forest_python"
	PkgName   string // actual Go package name from binding.go
	ImportPath string // full import path
}

func main() {
	forestDir := flag.String("forest-dir", "../../_tmp_sitter_forest/go-sitter-forest-main", "path to go-sitter-forest checkout")
	outFile := flag.String("out", "languages_forest.go", "output file name")
	flag.Parse()

	entries, err := scanForest(*forestDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error scanning forest: %v\n", err)
		os.Exit(1)
	}

	f, err := os.Create(*outFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error creating output: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	if err := generate(f, entries); err != nil {
		fmt.Fprintf(os.Stderr, "error generating: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "Generated %s with %d languages\n", *outFile, len(entries))
}

func scanForest(root string) ([]langEntry, error) {
	dirEntries, err := os.ReadDir(root)
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", root, err)
	}

	var entries []langEntry
	for _, de := range dirEntries {
		if !de.IsDir() {
			continue
		}
		dir := de.Name()
		if skipDirs[dir] {
			fmt.Fprintf(os.Stderr, "skipping %s (in skip list)\n", dir)
			continue
		}

		bindingPath := filepath.Join(root, dir, "binding.go")
		pkgName, err := extractPackageName(bindingPath)
		if err != nil {
			continue // no binding.go or unreadable — skip
		}

		alias := "forest_" + sanitizeAlias(dir)
		entries = append(entries, langEntry{
			Dir:        dir,
			Alias:      alias,
			PkgName:    pkgName,
			ImportPath: "github.com/alexaandru/go-sitter-forest/" + dir,
		})
	}

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Dir < entries[j].Dir
	})

	return entries, nil
}

func extractPackageName(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "package ") {
			return strings.TrimPrefix(line, "package "), nil
		}
	}
	return "", fmt.Errorf("no package line found in %s", path)
}

// sanitizeAlias makes a directory name safe as a Go identifier suffix.
func sanitizeAlias(dir string) string {
	// Go identifiers can't start with a digit, but with "forest_" prefix this is fine.
	// Just ensure no dashes (replace with underscore).
	return strings.ReplaceAll(dir, "-", "_")
}

var tmpl = template.Must(template.New("forest").Parse(`//go:build !lean

// Code generated by gen_forest.go; DO NOT EDIT.
// Generated: {{ .Timestamp }}
// Languages: {{ .Count }}

package treesitter

import (
	"unsafe"

	tree_sitter "github.com/tree-sitter/go-tree-sitter"
{{ range .Entries }}
	{{ .Alias }} "{{ .ImportPath }}"
{{- end }}
)

// langPtr wraps a GetLanguage() call that returns unsafe.Pointer.
func langPtr(p unsafe.Pointer) *tree_sitter.Language {
	return tree_sitter.NewLanguage(p)
}

// registerBuiltinLanguages adds all {{ .Count }} compiled-in grammars to the parser.
func (p *Parser) registerBuiltinLanguages() {
{{- range .Entries }}
	p.addLang("{{ .Dir }}", langPtr({{ .Alias }}.GetLanguage()))
{{- end }}
}
`))

func generate(w *os.File, entries []langEntry) error {
	data := struct {
		Entries   []langEntry
		Count     int
		Timestamp string
	}{
		Entries:   entries,
		Count:     len(entries),
		Timestamp: time.Now().UTC().Format(time.RFC3339),
	}
	return tmpl.Execute(w, data)
}
