version: 2

project_name: aoa

before:
  hooks:
    - go mod tidy
    - go vet ./...

builds:
  # aoa — pure Go binary (~7-12 MB, no CGo required)
  # File-level search works out of the box; symbol search requires aoa-recon.
  - id: aoa
    main: ./cmd/aoa/
    binary: aoa
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/corey/aoa/internal/version.Version={{.Version}}
      - -X github.com/corey/aoa/internal/version.BuildDate={{.Date}}

  # aoa-recon — CGo binary with tree-sitter grammars (~80 MB)
  # Adds symbol-level parsing and security scanning to the aoa index.
  - id: aoa-recon
    main: ./cmd/aoa-recon/
    binary: aoa-recon
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/corey/aoa/internal/version.Version={{.Version}}
      - -X github.com/corey/aoa/internal/version.BuildDate={{.Date}}
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc

archives:
  - id: aoa-archive
    builds: [aoa]
    formats: ['tar.gz']
    name_template: 'aoa-{{ .Version }}-{{ .Os }}-{{ .Arch }}'
  - id: aoa-recon-archive
    builds: [aoa-recon]
    formats: ['tar.gz']
    name_template: 'aoa-recon-{{ .Version }}-{{ .Os }}-{{ .Arch }}'

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: corey
    name: aoa
  draft: false
  prerelease: auto
  name_template: "aOa {{.Version}}"
  header: |
    ## aOa {{.Version}} — Two-Binary Release

    ### aoa (pure Go, ~8 MB)
    Search, learning, dashboard — works standalone. No CGo required.
    ```bash
    npm install -g aoa
    ```

    ### aoa-recon (CGo, ~80 MB)
    Tree-sitter parsing + security scanning. Enhances the aoa index with symbols.
    ```bash
    npm install -g aoa-recon
    ```

    aoa auto-discovers aoa-recon when both are installed.
